proxy:
  secretToken: "1ceceb779b78db81ad076c603e7924f8e6164cf87dfe92f4f8dc135b130932f4"

hub:
  config:
    DummyAuthenticator:
      password: custreamz
  extraConfig:
    rapidsConfig.py: |
      c.KubeSpawner.http_timeout = 1800
      c.KubeSpawner.start_timeout = 1800

auth:
  admin:
    access: true
    users:
      - kratos
cull:
  enabled: true
  timeout: 1800
  every: 600

singleuser:
  image:
    name: cschranz/gpu-jupyter
    tag: latest
  defaultUrl: "/lab"
  extraEnv:
    tenant: kratos
    profile: rapids-custreamz
  memory:
    guarantee: 4G
    limit: 4G
  cpu:
    guarantee: 1
    limit: 1
  storage:
    capacity: 10Gi
    dynamic:
      storageClass: gp2
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            cd /home/jovyan && git clone https://github.com/chinmaychandak/jupyterhub-tests.git;
            cp /home/jovyan/jupyterhub-tests/utilities/.condarc /home/jovyan;
            rm -rf /home/jovyan/jupyterhub-tests;
            conda install -y -q -c rapidsai -c nvidia -c conda-forge -c defaults custreamz=0.17 python=3.7 cudatoolkit=10.1;
  profileList:
    - display_name: "GPU-Jupyter + RAPIDS cuStreamz"
      description: "RAPIDS Profile based from GPU-Jupyter"
      default: true

    - display_name: "Spark ETL, ML"
      description: "Spark ETL, ML Profile"
      kubespawner_override:
        image: jupyter/minimal-notebook:latest
        environment:
          tenant: kratos
          profile: spark-etl-ml
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  cd /home/jovyan && git clone https://github.com/chinmaychandak/jupyterhub-tests.git;
                  cp /home/jovyan/jupyterhub-tests/utilities/.condarc /home/jovyan;
                  rm -rf /home/jovyan/jupyterhub-tests;

    # TODO
#    - display_name: "Base RAPIDS"
#      description: "RAPIDS-only Profile"
#      kubespawner_override:
#        image: rapidsai/rapidsai:0.17-cuda10.1-runtime-ubuntu18.04-py3.8
#        environment:
#          tenant: kratos
#          profile: base-rapids
#          JUPYTER_FG: true
#        lifecycle_hooks:
#          postStart:
#            exec:
#              command:
#                - "sh"
#                - "-c"
#                - >
#                  echo hello
